version: '3'
services:
  php:
    build:
      context: .
      dockerfile: './php/Dockerfile'
    env_file:
      - .env
    networks:
      - backend
  nginx:
    build:
      context: .
      dockerfile: './nginx/Dockerfile'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"   
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=cytaty
    volumes:
      - ~/db/mysql/data:/var/lib/mysql
      - ~/db/mysql/init:/docker-entrypoint-initdb.d/:ro
networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
