version: '3'
services:
  php:
    build:
      context: .
      dockerfile: './php/Dockerfile'
    env_file:
      - .env
    networks:
      - backend
  nginx:
    build:
      context: .
      dockerfile: './nginx/Dockerfile'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
  mysql:
    build:
      context: .
      dockerfile: './mysql/Dockerfile'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ~/data/mysql/data:/var/lib/mysql
      - ~/data/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  frontend:
    # external:
    #   name: nginx-proxy
  backend:
