version: '3'
services:
  php:
    build:
      context: .
      dockerfile: './php/Dockerfile'
    container_name: cytaty_php
    depends_on:
      - mysql  
    env_file:
      - .env
    networks:
      - backend
  nginx:
    build:
      context: .
      dockerfile: './nginx/Dockerfile'
    depends_on:
      - php
    container_name: cytaty_nginx
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    container_name: cytaty_mysql
    env_file:
      - .env
    volumes:
      - /data/db/cytatylegiecio/data:/var/lib/mysql
      - /data/db/cytatylegiecio/init/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
