# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:carbon
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: "Deploy image to Server"
            command: ssh -o StrictHostKeyChecking=no -l $SSH_USERNAME $SSH_HOST "$(echo "cd $CIRCLE_PROJECT_REPONAME && ./bin/restart.sh")"
